language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*

before_script:
    - curl -s http://getcomposer.org/installer | php
    - composer require symfony/http-foundation:${SYMFONY_VERSION} --no-update
    - php composer.phar --dev update

phpunit: php vendor/bin/phpunit

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover ./build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
